//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienTheSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienTheSanPham()
        {
            this.HinhAnhSanPhams = new HashSet<HinhAnhSanPham>();
            this.ThongSoBienTheDienThoais = new HashSet<ThongSoBienTheDienThoai>();
        }
    
        public int MaBT { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaMau { get; set; }
        public Nullable<int> MaRAM { get; set; }
        public Nullable<int> MaROM { get; set; }
        public int SoLuong { get; set; }
        public string DonViTinh { get; set; }
        public int DonGia { get; set; }
        public string SKU { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
    
        public virtual MauSac MauSac { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual ROM ROM { get; set; }
        public virtual TrangThaiSanPham TrangThaiSanPham { get; set; }
        public virtual SanPham SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnhSanPham> HinhAnhSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoBienTheDienThoai> ThongSoBienTheDienThoais { get; set; }
    }
}
