//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTinhNangCamera
    {
        public int MaChiTietTinhNangCamera { get; set; }
        public Nullable<int> MaTSBTDT { get; set; }
        public Nullable<int> MaLoaiCamera { get; set; }
        public Nullable<int> MaTinhNang { get; set; }
    
        public virtual LoaiCamera LoaiCamera { get; set; }
        public virtual TinhNang TinhNang { get; set; }
        public virtual ThongSoBienTheDienThoai ThongSoBienTheDienThoai { get; set; }
    }
}
