//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDoPhanGiaiManHinh
    {
        public int MaChiTietDoPhanGiai { get; set; }
        public Nullable<int> MaTSKT { get; set; }
        public Nullable<int> MaDoPhanGiai { get; set; }
        public int ChieuNgang { get; set; }
        public int ChieuDoc { get; set; }
    
        public virtual DoPhanGiaiManHinh DoPhanGiaiManHinh { get; set; }
        public virtual ThongSoKTDienThoai ThongSoKTDienThoai { get; set; }
    }
}
