//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhSanPham
    {
        public int MaHA { get; set; }
        public Nullable<int> MaBT { get; set; }
        public string DuongDanAnh { get; set; }
        public string TenAnh { get; set; }
        public Nullable<bool> AnhChinh { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
    }
}
