//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KichThuocKhoiLuong
    {
        public int MaKichThuocKhoiLuong { get; set; }
        public Nullable<int> MaTSKT { get; set; }
        public Nullable<double> ChieuDai { get; set; }
        public Nullable<double> ChieuNgang { get; set; }
        public Nullable<double> ChieuDay { get; set; }
        public Nullable<double> KhoiLuong { get; set; }
    
        public virtual ThongSoKTDienThoai ThongSoKTDienThoai { get; set; }
    }
}
