//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KichThuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KichThuoc()
        {
            this.KichThuocKhoiLuongs = new HashSet<KichThuocKhoiLuong>();
        }
    
        public int MaKichThuoc { get; set; }
        public Nullable<double> ChieuDai { get; set; }
        public Nullable<double> ChieuNgang { get; set; }
        public Nullable<double> DoDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KichThuocKhoiLuong> KichThuocKhoiLuongs { get; set; }
    }
}
