//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiKinhCuongLuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiKinhCuongLuc()
        {
            this.ThongTinKinhCuongLucDienThoais = new HashSet<ThongTinKinhCuongLucDienThoai>();
        }
    
        public int MaLoaiKinh { get; set; }
        public string TenLoaiKinh { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinKinhCuongLucDienThoai> ThongTinKinhCuongLucDienThoais { get; set; }
    }
}
