//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCHTBDD_62131904Entities : DbContext
    {
        public QLCHTBDD_62131904Entities()
            : base("name=QLCHTBDD_62131904Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QuanTriHeThong> QuanTriHeThongs { get; set; }
        public virtual DbSet<HinhAnhSanPham> HinhAnhSanPhams { get; set; }
        public virtual DbSet<BienTheSanPham> BienTheSanPhams { get; set; }
        public virtual DbSet<Bluetooth> Blueteeth { get; set; }
        public virtual DbSet<ChipXuLy> ChipXuLies { get; set; }
        public virtual DbSet<ChuanKhangBuiNuoc> ChuanKhangBuiNuocs { get; set; }
        public virtual DbSet<CongKetNoiKhac> CongKetNoiKhacs { get; set; }
        public virtual DbSet<CongKetNoiSac> CongKetNoiSacs { get; set; }
        public virtual DbSet<CongNgheGP> CongNgheGPS { get; set; }
        public virtual DbSet<CongNgheManHinhDienThoai> CongNgheManHinhDienThoais { get; set; }
        public virtual DbSet<CongNghePin> CongNghePins { get; set; }
        public virtual DbSet<CongNgheWifi> CongNgheWifis { get; set; }
        public virtual DbSet<CongNgheXemPhim> CongNgheXemPhims { get; set; }
        public virtual DbSet<DoPhanGiaiCamera> DoPhanGiaiCameras { get; set; }
        public virtual DbSet<HangSanXuat> HangSanXuats { get; set; }
        public virtual DbSet<HeDieuHanh> HeDieuHanhs { get; set; }
        public virtual DbSet<KichThuocKhoiLuong> KichThuocKhoiLuongs { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<MauSac> MauSacs { get; set; }
        public virtual DbSet<QuocGia> QuocGias { get; set; }
        public virtual DbSet<RAM> RAMs { get; set; }
        public virtual DbSet<ROM> ROMs { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<ThongSoCamera> ThongSoCameras { get; set; }
        public virtual DbSet<ThongSoKTDienThoai> ThongSoKTDienThoais { get; set; }
        public virtual DbSet<ThongSoQuayPhim> ThongSoQuayPhims { get; set; }
        public virtual DbSet<TinhNangCamera> TinhNangCameras { get; set; }
        public virtual DbSet<TinhNangDacBiet> TinhNangDacBiets { get; set; }
    }
}
