//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinPinVaSacDienThoai
    {
        public int MaThongTinPinSac { get; set; }
        public Nullable<int> MaTSKT { get; set; }
        public Nullable<int> MaLoaiPin { get; set; }
        public Nullable<int> MaDungLuongPin { get; set; }
        public Nullable<int> MaHoTroSac { get; set; }
    
        public virtual DungLuongPin DungLuongPin { get; set; }
        public virtual HoTroSacToiDa HoTroSacToiDa { get; set; }
        public virtual LoaiPin LoaiPin { get; set; }
        public virtual ThongSoKTDienThoai ThongSoKTDienThoai { get; set; }
    }
}
