//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoKTDienThoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongSoKTDienThoai()
        {
            this.CongNgheGPS = new HashSet<CongNgheGP>();
            this.CongNgheManHinhDienThoais = new HashSet<CongNgheManHinhDienThoai>();
            this.CongNghePins = new HashSet<CongNghePin>();
            this.CongNgheWifis = new HashSet<CongNgheWifi>();
            this.CongNgheXemPhims = new HashSet<CongNgheXemPhim>();
            this.KichThuocKhoiLuongs = new HashSet<KichThuocKhoiLuong>();
            this.ThongSoCameras = new HashSet<ThongSoCamera>();
            this.ThongSoQuayPhims = new HashSet<ThongSoQuayPhim>();
            this.TinhNangCameras = new HashSet<TinhNangCamera>();
            this.TinhNangDacBiets = new HashSet<TinhNangDacBiet>();
        }
    
        public int MaTSKT { get; set; }
        public Nullable<int> MaBT { get; set; }
        public Nullable<int> MaHDH { get; set; }
        public Nullable<int> MaChip { get; set; }
        public string TocDoCPU { get; set; }
        public string ChipDoHoaGPU { get; set; }
        public string DungLuongConLai { get; set; }
        public Nullable<bool> DanhBa { get; set; }
        public Nullable<bool> DenFlashCameraSau { get; set; }
        public string DoPhanGiaiManHinh { get; set; }
        public string KichThuocManHinh { get; set; }
        public string DoSangToiDa { get; set; }
        public string MatKinhCamUng { get; set; }
        public string DungLuongPin { get; set; }
        public string LoaiPin { get; set; }
        public string HoTroSacToiDa { get; set; }
        public string BaoMatNangCao { get; set; }
        public Nullable<int> MaChuanKhangBuiNuoc { get; set; }
        public string GhiAm { get; set; }
        public Nullable<bool> NgheNhac { get; set; }
        public string MangDiDong { get; set; }
        public string SIM { get; set; }
        public Nullable<int> MaBluetooth { get; set; }
        public Nullable<int> MaCongKetNoiSac { get; set; }
        public Nullable<bool> JackTaiNghe { get; set; }
        public Nullable<int> MaCongKetNoiKhac { get; set; }
        public string ThietKe { get; set; }
        public string ChatLieu { get; set; }
        public Nullable<System.DateTime> ThoiDiemRaMat { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        public virtual Bluetooth Bluetooth { get; set; }
        public virtual ChipXuLy ChipXuLy { get; set; }
        public virtual ChuanKhangBuiNuoc ChuanKhangBuiNuoc { get; set; }
        public virtual CongKetNoiKhac CongKetNoiKhac { get; set; }
        public virtual CongKetNoiSac CongKetNoiSac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongNgheGP> CongNgheGPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongNgheManHinhDienThoai> CongNgheManHinhDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongNghePin> CongNghePins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongNgheWifi> CongNgheWifis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongNgheXemPhim> CongNgheXemPhims { get; set; }
        public virtual HeDieuHanh HeDieuHanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KichThuocKhoiLuong> KichThuocKhoiLuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoCamera> ThongSoCameras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoQuayPhim> ThongSoQuayPhims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinhNangCamera> TinhNangCameras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinhNangDacBiet> TinhNangDacBiets { get; set; }
    }
}
