//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinManHinhDienThoai
    {
        public int MaThongTinManHinh { get; set; }
        public Nullable<int> MaTSKT { get; set; }
        public Nullable<int> MaKichThuocManHinh { get; set; }
        public Nullable<int> MaTanSoQuet { get; set; }
    
        public virtual KichThuocManHinh KichThuocManHinh { get; set; }
        public virtual TanSoQuetManHinh TanSoQuetManHinh { get; set; }
        public virtual ThongSoKTDienThoai ThongSoKTDienThoai { get; set; }
    }
}
