//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThongSoKTDienThoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongSoKTDienThoai()
        {
            this.ChiTietDoPhanGiaiManHinhs = new HashSet<ChiTietDoPhanGiaiManHinh>();
            this.ChiTietTinhNangCameras = new HashSet<ChiTietTinhNangCamera>();
            this.KichThuocKhoiLuongs = new HashSet<KichThuocKhoiLuong>();
            this.ThongSoCameras = new HashSet<ThongSoCamera>();
            this.ThongSoQuayPhims = new HashSet<ThongSoQuayPhim>();
            this.ThongTinBaoMatNangCaoDienThoais = new HashSet<ThongTinBaoMatNangCaoDienThoai>();
            this.ThongTinCongNghePinDienThoais = new HashSet<ThongTinCongNghePinDienThoai>();
            this.ThongTinCongNgheManHinhDienThoais = new HashSet<ThongTinCongNgheManHinhDienThoai>();
            this.ThongTinDinhDangPhimVaNhacDienThoais = new HashSet<ThongTinDinhDangPhimVaNhacDienThoai>();
            this.ThongTinDoSangDienThoais = new HashSet<ThongTinDoSangDienThoai>();
            this.ThongTinHeThongDinhViDienThoais = new HashSet<ThongTinHeThongDinhViDienThoai>();
            this.ThongTinKinhCuongLucDienThoais = new HashSet<ThongTinKinhCuongLucDienThoai>();
            this.ThongTinMangDiDongDienThoais = new HashSet<ThongTinMangDiDongDienThoai>();
            this.ThongTinManHinhDienThoais = new HashSet<ThongTinManHinhDienThoai>();
            this.ThongTinPinVaSacDienThoais = new HashSet<ThongTinPinVaSacDienThoai>();
            this.ThongTinTinhNangDacBietDienThoais = new HashSet<ThongTinTinhNangDacBietDienThoai>();
            this.ThongTinWifiDienThoais = new HashSet<ThongTinWifiDienThoai>();
        }
    
        public int MaTSKT { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaPhienBanHDH { get; set; }
        public Nullable<int> MaChip { get; set; }
        public Nullable<int> MaTocDoCPU { get; set; }
        public Nullable<int> MaChipDoHoaGPU { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập dung lượng còn lại.")]
        [RegularExpression(@"^\d+(GB|MB)?$", ErrorMessage = "Dung lượng phải là số và có đơn vị (GB hoặc MB).")]
        public string DungLuongConLai { get; set; }
        public Nullable<bool> DanhBa { get; set; }
        public Nullable<bool> DenFlashCameraSau { get; set; }
        public Nullable<int> MaChuanKhangBuiNuoc { get; set; }
        public Nullable<int> MaDinhDangGhiAm { get; set; }
        public Nullable<int> MaSIM { get; set; }
        public Nullable<int> MaBluetooth { get; set; }
        public Nullable<int> MaCongKetNoiSac { get; set; }
        public Nullable<int> MaJackTaiNghe { get; set; }
        public Nullable<int> MaCongKetNoiKhac { get; set; }
        public Nullable<int> MaThietKe { get; set; }
        public Nullable<int> MaChatLieu { get; set; }
        [Required(ErrorMessage = "Thời điểm ra mắt là bắt buộc.")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ThoiDiemRaMat { get; set; }
    
        public virtual Bluetooth Bluetooth { get; set; }
        public virtual ChatLieu ChatLieu { get; set; }
        public virtual ChipDoHoaGPU ChipDoHoaGPU { get; set; }
        public virtual ChipXuLy ChipXuLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDoPhanGiaiManHinh> ChiTietDoPhanGiaiManHinhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTinhNangCamera> ChiTietTinhNangCameras { get; set; }
        public virtual ChuanKhangBuiNuoc ChuanKhangBuiNuoc { get; set; }
        public virtual CongKetNoiKhac CongKetNoiKhac { get; set; }
        public virtual CongKetNoiSac CongKetNoiSac { get; set; }
        public virtual DinhDangGhiAm DinhDangGhiAm { get; set; }
        public virtual JackTaiNghe JackTaiNghe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KichThuocKhoiLuong> KichThuocKhoiLuongs { get; set; }
        public virtual PhienBanHDH PhienBanHDH { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual SIM SIM { get; set; }
        public virtual ThietKe ThietKe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoCamera> ThongSoCameras { get; set; }
        public virtual TocDoCPU TocDoCPU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoQuayPhim> ThongSoQuayPhims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinBaoMatNangCaoDienThoai> ThongTinBaoMatNangCaoDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinCongNghePinDienThoai> ThongTinCongNghePinDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinCongNgheManHinhDienThoai> ThongTinCongNgheManHinhDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinDinhDangPhimVaNhacDienThoai> ThongTinDinhDangPhimVaNhacDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinDoSangDienThoai> ThongTinDoSangDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinHeThongDinhViDienThoai> ThongTinHeThongDinhViDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinKinhCuongLucDienThoai> ThongTinKinhCuongLucDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinMangDiDongDienThoai> ThongTinMangDiDongDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinManHinhDienThoai> ThongTinManHinhDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinPinVaSacDienThoai> ThongTinPinVaSacDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinTinhNangDacBietDienThoai> ThongTinTinhNangDacBietDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinWifiDienThoai> ThongTinWifiDienThoais { get; set; }
    }
}
