//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoBienTheDienThoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongSoBienTheDienThoai()
        {
            this.ChiTietTinhNangCameras = new HashSet<ChiTietTinhNangCamera>();
            this.ThongSoCameras = new HashSet<ThongSoCamera>();
            this.ThongSoQuayPhims = new HashSet<ThongSoQuayPhim>();
            this.ThongTinCongNghePinDienThoais = new HashSet<ThongTinCongNghePinDienThoai>();
            this.ThongTinDinhDangPhimVaNhacDienThoais = new HashSet<ThongTinDinhDangPhimVaNhacDienThoai>();
            this.ThongTinHeThongDinhViDienThoais = new HashSet<ThongTinHeThongDinhViDienThoai>();
            this.ThongTinTinhNangDacBietDienThoais = new HashSet<ThongTinTinhNangDacBietDienThoai>();
            this.ThongTinWifiDienThoais = new HashSet<ThongTinWifiDienThoai>();
        }
    
        public int MaTSBTDT { get; set; }
        public Nullable<int> MaBT { get; set; }
        public Nullable<int> MaChip { get; set; }
        public Nullable<int> MaTocDoCPU { get; set; }
        public Nullable<int> MaChipDoHoaGPU { get; set; }
        public string DungLuongConLai { get; set; }
        public Nullable<int> MaDoPhanGiai { get; set; }
        public Nullable<int> MaPixelNgang { get; set; }
        public Nullable<int> MaPixelDoc { get; set; }
        public Nullable<int> MaKichThuocManHinh { get; set; }
        public Nullable<int> MaTanSoQuet { get; set; }
        public Nullable<int> MaDungLuongPin { get; set; }
        public Nullable<int> MaChieuDai { get; set; }
        public Nullable<int> MaChieuNgang { get; set; }
        public Nullable<int> MaDoDay { get; set; }
        public Nullable<int> MaKhoiLuong { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        public virtual ChieuDai ChieuDai { get; set; }
        public virtual ChieuNgang ChieuNgang { get; set; }
        public virtual ChipDoHoaGPU ChipDoHoaGPU { get; set; }
        public virtual ChipXuLy ChipXuLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTinhNangCamera> ChiTietTinhNangCameras { get; set; }
        public virtual DoDay DoDay { get; set; }
        public virtual DoPhanGiaiManHinh DoPhanGiaiManHinh { get; set; }
        public virtual DungLuongPin DungLuongPin { get; set; }
        public virtual KhoiLuong KhoiLuong { get; set; }
        public virtual KichThuocManHinh KichThuocManHinh { get; set; }
        public virtual PixelDoc PixelDoc { get; set; }
        public virtual PixelNgang PixelNgang { get; set; }
        public virtual TanSoQuetManHinh TanSoQuetManHinh { get; set; }
        public virtual TocDoCPU TocDoCPU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoCamera> ThongSoCameras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoQuayPhim> ThongSoQuayPhims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinCongNghePinDienThoai> ThongTinCongNghePinDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinDinhDangPhimVaNhacDienThoai> ThongTinDinhDangPhimVaNhacDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinHeThongDinhViDienThoai> ThongTinHeThongDinhViDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinTinhNangDacBietDienThoai> ThongTinTinhNangDacBietDienThoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinWifiDienThoai> ThongTinWifiDienThoais { get; set; }
    }
}
