//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoKiThuat
    {
        public int MaTSKT { get; set; }
        public string ManHinh { get; set; }
        public string Camera { get; set; }
        public string Pin { get; set; }
        public string Chipset { get; set; }
        public string RAM { get; set; }
        public string HeDieuHanh { get; set; }
        public Nullable<int> MaBienThe { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
    }
}
