//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoCamera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongSoCamera()
        {
            this.ChiTietDoPhanGiaiCameras = new HashSet<ChiTietDoPhanGiaiCamera>();
        }
    
        public int MaThongSoCamera { get; set; }
        public Nullable<int> MaTSBTDT { get; set; }
        public Nullable<int> MaLoaiCamera { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDoPhanGiaiCamera> ChiTietDoPhanGiaiCameras { get; set; }
        public virtual LoaiCamera LoaiCamera { get; set; }
        public virtual ThongSoBienTheDienThoai ThongSoBienTheDienThoai { get; set; }
    }
}
