//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTBDD_62131904.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoDienThoai
    {
        public int MaTSDT { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaPhienBanHDH { get; set; }
        public Nullable<bool> DanhBa { get; set; }
        public Nullable<bool> DenFlashCameraSau { get; set; }
        public Nullable<int> MaChuanKhangBuiNuoc { get; set; }
        public Nullable<int> MaCongNgheManHinh { get; set; }
        public Nullable<int> MaDoSang { get; set; }
        public Nullable<int> MaLoaiKinh { get; set; }
        public Nullable<int> MaLoaiPin { get; set; }
        public Nullable<int> MaHoTroSac { get; set; }
        public Nullable<int> MaTinhNangBaoMat { get; set; }
        public Nullable<int> MaDinhDangGhiAm { get; set; }
        public Nullable<int> MaMangDiDong { get; set; }
        public Nullable<int> MaSIM { get; set; }
        public Nullable<int> MaBluetooth { get; set; }
        public Nullable<int> MaCongKetNoiSac { get; set; }
        public Nullable<int> MaJackTaiNghe { get; set; }
        public Nullable<int> MaCongKetNoiKhac { get; set; }
        public Nullable<int> MaThietKe { get; set; }
        public Nullable<int> MaChatLieu { get; set; }
        public Nullable<System.DateTime> ThoiDiemRaMat { get; set; }
    
        public virtual Bluetooth Bluetooth { get; set; }
        public virtual ChatLieu ChatLieu { get; set; }
        public virtual ChuanKhangBuiNuoc ChuanKhangBuiNuoc { get; set; }
        public virtual CongKetNoiKhac CongKetNoiKhac { get; set; }
        public virtual CongKetNoiSac CongKetNoiSac { get; set; }
        public virtual CongNgheManHinh CongNgheManHinh { get; set; }
        public virtual DinhDangGhiAm DinhDangGhiAm { get; set; }
        public virtual DoSangToiDa DoSangToiDa { get; set; }
        public virtual HoTroSacToiDa HoTroSacToiDa { get; set; }
        public virtual JackTaiNghe JackTaiNghe { get; set; }
        public virtual LoaiKinhCuongLuc LoaiKinhCuongLuc { get; set; }
        public virtual LoaiPin LoaiPin { get; set; }
        public virtual MangDiDong MangDiDong { get; set; }
        public virtual PhienBanHDH PhienBanHDH { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual SIM SIM { get; set; }
        public virtual ThietKe ThietKe { get; set; }
        public virtual TinhNangBaoMat TinhNangBaoMat { get; set; }
    }
}
